# Generated by Django 3.0.4 on 2020-04-25 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_datisdlogs_datiswlogs_dscndlogs_employee_mcdo_vhfdlogs_vhfmlogs_vhfylogs'),
    ]

    operations = [
        migrations.CreateModel(
            name='DgmReports',
            fields=[
                ('r_id', models.IntegerField(primary_key=True, serialize=False)),
                ('r_type', models.CharField(max_length=30)),
                ('r_status', models.CharField(max_length=30)),
                ('r_count', models.PositiveIntegerField()),
                ('r_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'dgmreports',
                'managed': False,
            },
        ),
    ]
